export const POSTS_REQUESTED = 'POSTS_REQUESTED';
export const POSTS_RECEIVED = 'POSTS_RECEIVED';
export const POSTS_FAILED = 'POSTS_FAILED';

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAILED = 'POST_CREATE_FAILED';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
export const VERIFY_REQUEST = 'VERIFY_REQUEST';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const USER_REQUESTED = 'USER_REQUESTED';
export const USER_RECEIVED = 'USER_RECEIVED';
export const USER_FAILED = 'USER_FAILED';

export const USER_EDIT_REQUESTED = 'USER_EDIT_REQUESTED';
export const USER_EDIT_RECEIVED = 'USER_EDIT_RECEIVED';
export const USER_EDIT_FAILED = 'USER_EDIT_FAILED';
