export const POSTS_REQUESTED = 'POSTS_REQUESTED';
export const POSTS_RECEIVED = 'POSTS_RECEIVED';
export const POSTS_FAILED = 'POSTS_FAILED';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
export const VERIFY_REQUEST = 'VERIFY_REQUEST';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const LOGOUT = 'LOGOUT';